<a href="https://colab.research.google.com/github/rudxkush/Machine-Learning/blob/main/Python/numpy101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import numpy as np
# It provides high performance multi-dimensional array objects (ndarray)

# Examples:
# - 2D array (array of arrays of float) → weight matrix in attention mechanism
# - 3D array → batch_size x sequence_length x embedding_dimension tensor

In [116]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]

arr = np.array(lst);
print(type(arr));
print(arr);
print(arr.shape)


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
(9,)


In [117]:
lst1 = [1, 2, 3, 4]
lst2 = [5, 6, 7, 8]
lst3 = [9, 10, 11, 12]

mat = np.array([lst1, lst2, lst3]);
print(type(mat));
print(mat);
print(mat.shape)


<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [118]:
print(arr.reshape(3, 3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [119]:
print(mat)
print(mat[0:2, 0:2]) # matrix(start_row, end_row + 1, start_col, end_col + 1)
print(mat[2:, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[11 12]]


In [120]:
original = arr;
arr = np.arange(0,10,step=2);
print(arr)
print(original);

[0 2 4 6 8]
[1 2 3 4 5 6 7 8 9]


In [121]:
np.linspace(1, 10, 50)
# Creates 50 equally spaced numbers between 1 and 10 (inclusive).
# Used in - Creating synthetic datasets, Plotting functions

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [122]:
original[3:]=100
print(original)

[  1   2   3 100 100 100 100 100 100]


In [123]:
copy_arr = original
copy_arr[3:] = 500
print(copy_arr)
print(original) # As array is a reference type, both are accessing the same shared memory space

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500]


In [124]:
copy_arr = original.copy() # Another memory block is allocated with the same values and shape as original array
copy_arr[3:] = 1000
print(copy_arr)
print(original)

[   1    2    3 1000 1000 1000 1000 1000 1000]
[  1   2   3 500 500 500 500 500 500]


In [134]:
print(arr[arr > 1])
print(arr * 3)

[2 4 6 8]
[ 0  6 12 18 24]


In [140]:
print(np.arange(0, 10).reshape(2, 5)) # create arrays and reshape

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [141]:
np.ones(4, dtype=int) # creates an array where are the elements are replaced by 1s, by default the type is float

array([1., 1., 1., 1.])

In [144]:
# Random Distribution
rand_arr = np.random.randint(0, 10, 20)
print(rand_arr)

[4 0 6 6 2 8 9 5 3 3 0 6 3 2 0 5 4 1 3 9]
