<a href="https://colab.research.google.com/github/rudxkush/Machine-Learning/blob/main/Python/numpy101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import numpy as np
# It provides high performance multi-dimensional array objects (ndarray)

# Examples:
# - 2D array (array of arrays of float) → weight matrix in attention mechanism
# - 3D array → batch_size x sequence_length x embedding_dimension tensor

In [62]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]

arr = np.array(lst);
print(type(arr));
print(arr);
print(arr.shape)


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
(9,)


In [63]:
lst1 = [1, 2, 3, 4]
lst2 = [5, 6, 7, 8]
lst3 = [9, 10, 11, 12]

mat = np.array([lst1, lst2, lst3]);
print(type(mat));
print(mat);
print(mat.shape)


<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [64]:
print(arr.reshape(3, 3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
print(mat)
print(mat[0:2, 0:2]) # matrix(start_row, end_row + 1, start_col, end_col + 1)
print(mat[2:, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [5 6]]
[[11 12]]


In [66]:
arr = np.arange(0,10,step=2);
print(arr)

[0 2 4 6 8]
